NavfnROS:
  allow_unknown: true
  default_tolerance: 0.1
  visualize_potential: true   # false

GlobalPlanner:
    allow_unknown: true
    use_dijkstra: true
    use_quadratic: true
    visualize_potential: true
    use_grid_path: false
    old_navfn_behavior: false
    cost_factor: 0.55
    neutral_cost: 66
    lethal_cost: 253
    default_tolerance: 0.5

TrajectoryPlannerROS:
  #Robot Configuration Parameters
    max_vel_x: 0.45
    min_vel_x: 0.1
    max_vel_theta: 1.0
    min_in_place_vel_theta: 0.4
    escape_vel: -0.3



    acc_lim_theta: 1.0
    acc_lim_x: 1.0
    acc_lim_y: 0.0

    holonomic_robot: false

  #Goal Tolerance Parameters
    yaw_goal_tolerance: 0.1 #default 0.05
    xy_goal_tolerance: 0.2 #default 0.1
  #Trajectory Scoring Parameters
    pdist_scale:  0.6
    gdist_scale:  0.8
    occdist_scal: 0.02 #default 0.01



DWAPlannerROS:


# Robot Configuration Parameters - Kobuki
  max_vel_x: 0.55  # 0.55
  min_vel_x: -0.1

  max_vel_y: 0.0  # diff drive robot
  min_vel_y: 0.0  # diff drive robot

  max_trans_vel: 0.5 # choose slightly less than the base's capability
  min_trans_vel: -0.4  # this is the min trans velocity when there is negligible rotational velocity
  trans_stopped_vel: 0.05

  # Warning!
  #   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  #   are non-negligible and small in place rotational velocities will be created.

  max_rot_vel: 1.0  # choose slightly less than the base's capability
  min_rot_vel: 1.0  # this is the min angular velocity when there is negligible translational velocity
  rot_stopped_vel: 0.07

  acc_lim_x: 1.2 # maximum is theoretically 2.0, but we
  acc_lim_theta: 1.5
  acc_lim_y: 0.0      # diff drive robot

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3  # 0.05
  xy_goal_tolerance: 0.3  # 0.10
  latch_xy_goal_tolerance: true

# Forward Simulation Parameters
  sim_time: 3.3       # 1.7
  vx_samples: 16       # 3
  vy_samples: 1       # diff drive robot, there is only one sample
  vtheta_samples: 30  # 20

# Trajectory Scoring Parameters
  path_distance_bias: 32.0      # 32.0   - weighting for how much it should stick to the global path plan
  goal_distance_bias: 22.0      # 24.0   - wighting for how much it should attempt to reach its goal
  occdist_scale: 0.03            # 0.01   - weighting for how much the controller should avoid obstacles
  forward_point_distance: 0.325 # 0.325  - how far along to place an additional scoring point
  stop_time_buffer: 0.5         # 0.2    - amount of time a robot must stop in before colliding for a valid traj.
  scaling_speed: 0.25           # 0.25   - absolute velocity at which to start scaling the robot's footprint
  max_scaling_factor: 0.2       # 0.2    - how much to scale the robot ...
  oscillation_reset_dist: 0.08
