global_frame: /map
robot_base_frame: base_link
obstacle_range: 6.5
raytrace_range: 7.5
resolution: 0.05
transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 5.0
footprint: [ [0.3602, -0.0708], [0.274, -0.0708], [0.274, -0.254], [-0.274, -0.274], [-0.274, 0.274], [0.274, 0.274], [0.274, 0.0708], [0.3602, 0.0708] ]
footprint_padding: 0.1
plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  obstacle_range: 6.5
  raytrace_range: 7.5
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true, raytrace_range: 7.5, obstacle_range: 6.5}
  track_unknown_space: true
inflater_layer:
 inflation_radius: 1.2
 cost_scaling_factor: 2.58
