footprint: [[-0.32, -0.2], [-0.32, 0.2], [0.32, 0.2], [0.32, -0.2]]
footprint_padding: 0.05
robot_base_frame: base_link
update_frequency: 7.0
publish_frequency: 4.0
transform_tolerance: 0.5
rolling_window: true
static_map: false
resolution: 0.05

obstacle_range: 6.5
raytrace_range: 7.0
plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  obstacle_range: 6.5
  raytrace_range: 7.5
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true, raytrace_range: 7.5, obstacle_range: 6.5}
  track_unknown_space: true
inflater_layer:
 inflation_radius: 1.2
 cost_scaling_factor: 2.58
