footprint: [ [0.3602, -0.0708], [0.274, -0.0708], [0.274, -0.254], [-0.274, -0.274], [-0.274, 0.274], [0.274, 0.274], [0.274, 0.0708], [0.3602, 0.0708] ]
footprint_padding: 0.1
transform_tolerance:    1.5
update_frequency: 3.5
publish_frequency: 2.0

static:
  unknown_cost_value:        -1
  lethal_cost_threshold:     100
  map_topic:                 map
  subscribe_to_updates:      true
  track_unknown_space: true


obstacles_costmap2d:
  track_unknown_space: true
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: hokuyo_frame, data_type: LaserScan, topic: hokuyo, marking: true, clearing: true, raytrace_range: 7.5, obstacle_range: 6.5}

obstacles_voxel_grid:
  origin_z:              0.0
  z_resolution:          0.2
  z_voxels:              10
  unknown_threshold:     5
  mark_threshold:        0
  publish_voxel_map:     true
  observation_sources:   point_cloud_sensor
  point_cloud_sensor:  {topic: camera/depth/points,
                       data_type:               PointCloud2,
                       expected_update_rate:    0.9,
                       observation_persistence: 0.0,
                       marking:                 true,
                       clearing:                true,
                       inf_is_valid:            false,
                       min_obstacle_height:     0.0,
                       max_obstacle_height:     2.0,
                       obstacle_range:          5.5,
                       raytrace_range: 6.0}

inflation:
  inflation_radius: 1.5
  cost_scaling_factor: 2.3
