map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

global_frame: /map
robot_base_frame: base_link



obstacle_range: 5.5
raytrace_range: 3.5




footprint: [ [0.3602, -0.0708], [0.274, -0.0708], [0.274, -0.254], [-0.274, -0.274], [-0.274, 0.274], [0.274, 0.274], [0.274, 0.0708], [0.3602, 0.0708] ]
footprint_padding: 0.1

plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true }

inflater_layer:
 inflation_radius: 0.60







map_topic: map
#subscribe_to_updates: true
