track_unknown_space: true
global_frame: /map
rolling_window: false
robot_base_frame: base_link
resolution: 0.05
width: 40.0
height: 40.0
origin_x: -20.0
origin_y: -20.0
transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 5.0
footprint: [ [0.3602, -0.0708], [0.274, -0.0708], [0.274, -0.254], [-0.274, -0.274], [-0.274, 0.274], [0.274, 0.274], [0.274, 0.0708], [0.3602, 0.0708] ]
footprint_padding: 0.1
plugins:
- {name: explore_boundary,    type: "frontier_exploration::BoundedExploreLayer"}
#Can disable sensor layer if gmapping is fast enough to update scans
- {name: obstacles_laser,     type: "costmap_2d::ObstacleLayer"}
- {name: inflation,           type: "costmap_2d::InflationLayer"}

explore_boundary:
  resize_to_boundary: false
  frontier_travel_point: closest
  #set to false for gmapping, true if re-exploring a known area
  explore_clear_space: false
obstacles_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true, raytrace_range: 6.5, obstacle_range: 5.5}
  track_unknown_space: true
inflater_layer:
 inflation_radius: 1.0
