global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 5
  static_map: false
  rolling_window: true
  width: 40.0
  height: 40.0
  origin_x: -20.0
  origin_y: -20.0
  plugins:
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
